/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.City;
import BL.Reminders;
import BL.Users;
import DAL.Exceptions;
import DAL.RemindersRepository;
import DAL.UsersRepository;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ardian
 */
public class AddReg extends javax.swing.JFrame {
    UsersRepository userRepo = new UsersRepository();
    RemindersRepository remindRepo = new RemindersRepository();
    Users user = new Users();;
    boolean isset = false;

    /**
     * Creates new form AddReg
     */
    public AddReg() {
        initComponents();
        this.setLocationRelativeTo(null);
        condJlabel.setVisible(false);
        cityText.setVisible(false);
        celsious.setVisible(false);
        temp.setVisible(false);
        jseperatorTemp.setVisible(false);
        celsious.setVisible(false);
        city.setVisible(false);
        cityBorder.setVisible(false);
    }
    
    public void checkUser(String username, String password){
        try{
            
        user.setUsername(username);
        user.setPassword(password);

        }catch(Exception e){
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWeather1 = new javax.swing.JButton();
        addReminder = new javax.swing.JButton();
        city = new javax.swing.JTextField();
        cityBorder = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        temp = new javax.swing.JTextField();
        jseperatorTemp = new javax.swing.JSeparator();
        celsious = new javax.swing.JLabel();
        dateYear = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        addWeather = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateMonth = new javax.swing.JComboBox();
        condJlabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        dateDay = new javax.swing.JTextField();
        cityText = new javax.swing.JLabel();
        shared = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 520));
        setMinimumSize(new java.awt.Dimension(400, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addWeather1.setBackground(new java.awt.Color(255, 102, 102));
        addWeather1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addWeather1.setForeground(new java.awt.Color(255, 255, 255));
        addWeather1.setText("Anulo");
        addWeather1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        addWeather1.setBorderPainted(false);
        addWeather1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addWeather1.setMaximumSize(new java.awt.Dimension(80, 35));
        addWeather1.setMinimumSize(new java.awt.Dimension(80, 35));
        addWeather1.setOpaque(false);
        addWeather1.setPreferredSize(new java.awt.Dimension(80, 35));
        addWeather1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWeather1ActionPerformed(evt);
            }
        });
        getContentPane().add(addWeather1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        addReminder.setBackground(new java.awt.Color(102, 153, 0));
        addReminder.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addReminder.setForeground(new java.awt.Color(255, 255, 255));
        addReminder.setText("Ruaj");
        addReminder.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        addReminder.setBorderPainted(false);
        addReminder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addReminder.setMaximumSize(new java.awt.Dimension(80, 35));
        addReminder.setMinimumSize(new java.awt.Dimension(80, 35));
        addReminder.setOpaque(false);
        addReminder.setPreferredSize(new java.awt.Dimension(80, 35));
        addReminder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReminderActionPerformed(evt);
            }
        });
        getContentPane().add(addReminder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        city.setBackground(new java.awt.Color(0, 0, 0, 0));
        city.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        city.setBorder(null);
        city.setCaretColor(new java.awt.Color(255, 255, 255));
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 140, 20));
        getContentPane().add(cityBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 140, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 10));

        title.setBackground(new java.awt.Color(0, 0, 0, 0));
        title.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setBorder(null);
        title.setCaretColor(new java.awt.Color(255, 255, 255));
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, 20));

        jLabel1.setBackground(new java.awt.Color(32, 33, 35));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Titulli");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(32, 33, 35));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pershkrimi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        desc.setColumns(20);
        desc.setFont(new java.awt.Font("Calibri", 0, 14));
        desc.setLineWrap(true);
        desc.setRows(5);
        desc.setWrapStyleWord(true);
        jScrollPane1.setViewportView(desc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 220, 150));

        temp.setBackground(new java.awt.Color(0, 0, 0, 0));
        temp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        temp.setForeground(new java.awt.Color(255, 255, 255));
        temp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        temp.setBorder(null);
        temp.setCaretColor(new java.awt.Color(255, 255, 255));
        temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempActionPerformed(evt);
            }
        });
        getContentPane().add(temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 50, 20));
        getContentPane().add(jseperatorTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 50, 10));

        celsious.setBackground(new java.awt.Color(32, 33, 35));
        celsious.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        celsious.setForeground(new java.awt.Color(255, 255, 255));
        celsious.setText("°C");
        getContentPane().add(celsious, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        dateYear.setBackground(new java.awt.Color(0, 0, 0, 0));
        dateYear.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        dateYear.setForeground(new java.awt.Color(255, 255, 255));
        dateYear.setBorder(null);
        dateYear.setCaretColor(new java.awt.Color(255, 255, 255));
        dateYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateYearActionPerformed(evt);
            }
        });
        getContentPane().add(dateYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 60, 20));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setMaximumSize(new java.awt.Dimension(0, 1));
        jSeparator3.setMinimumSize(new java.awt.Dimension(0, 1));
        jSeparator3.setOpaque(true);
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 60, -1));

        addWeather.setBackground(new java.awt.Color(51, 102, 255));
        addWeather.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addWeather.setForeground(new java.awt.Color(255, 255, 255));
        addWeather.setText("Shto motin");
        addWeather.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        addWeather.setBorderPainted(false);
        addWeather.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addWeather.setOpaque(false);
        addWeather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWeatherActionPerformed(evt);
            }
        });
        getContentPane().add(addWeather, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel4.setBackground(new java.awt.Color(32, 33, 35));
        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel5.setBackground(new java.awt.Color(32, 33, 35));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        dateMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muaji", "Janar", "Shkurt", "Mars", "Prill", "Maj", "Qershor", "Korrik", "Gusht", "Shtator", "Tetor", "Nentor", "Dhjetor" }));
        dateMonth.setMaximumSize(new java.awt.Dimension(56, 18));
        dateMonth.setMinimumSize(new java.awt.Dimension(56, 18));
        dateMonth.setName(""); // NOI18N
        dateMonth.setPreferredSize(new java.awt.Dimension(56, 18));
        dateMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateMonthActionPerformed(evt);
            }
        });
        getContentPane().add(dateMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 130, 30));

        condJlabel.setBackground(new java.awt.Color(32, 33, 35));
        condJlabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        condJlabel.setForeground(new java.awt.Color(255, 255, 255));
        condJlabel.setText("Nese temperatura eshte me lartë se:");
        getContentPane().add(condJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOpaque(true);
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 60, -1));

        dateDay.setBackground(new java.awt.Color(0, 0, 0, 0));
        dateDay.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        dateDay.setForeground(new java.awt.Color(255, 255, 255));
        dateDay.setBorder(null);
        dateDay.setCaretColor(new java.awt.Color(255, 255, 255));
        dateDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDayActionPerformed(evt);
            }
        });
        getContentPane().add(dateDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 60, 20));

        cityText.setBackground(new java.awt.Color(32, 33, 35));
        cityText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cityText.setForeground(new java.awt.Color(255, 255, 255));
        cityText.setText("ne Qytetin:");
        getContentPane().add(cityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        shared.setForeground(new java.awt.Color(255, 255, 255));
        shared.setText("Publike");
        shared.setOpaque(false);
        getContentPane().add(shared, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 90, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/WDF_778052.jpg"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(450, 300));
        jLabel8.setMinimumSize(new java.awt.Dimension(450, 300));
        jLabel8.setPreferredSize(new java.awt.Dimension(450, 300));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    private void addWeatherActionPerformed(java.awt.event.ActionEvent evt) {
        condJlabel.setVisible(true);
        celsious.setVisible(true);
        temp.setVisible(true);
        jseperatorTemp.setVisible(true);
        celsious.setVisible(true);
        cityText.setVisible(true);
        city.setVisible(true);
        cityBorder.setVisible(true);
        addWeather.setVisible(false);
        
        isset = true;
    }


    private void addWeather1ActionPerformed(java.awt.event.ActionEvent evt) {
                
        try {
            Home h = new Home();
            h.checkUser(user.getUsername(), user.getPassword());
            h.setVisible(true);
            dispose();
        } catch (Exception ex) {
            System.exit(0);
        }
                
    }
    

    private void addReminderActionPerformed(java.awt.event.ActionEvent evt){
        //String title,desc,dateDay,dateMonth,dateYear;
        String reminderTitle = title.getText();
        String reminderDesc = desc.getText();
        String reminderDay = dateDay.getText();
        String reminderMonth = (String) dateMonth.getSelectedItem();
        reminderMonth = userRepo.monthString(reminderMonth);
        String reminderYear = dateYear.getText();
        String reminderTemp = temp.getText();
        Short temp = null;
        
        boolean share = shared.isSelected();

        
        Date date = null;
        Date today = new Date();
        DateFormat df = new SimpleDateFormat("dd MM yyyy");
        
        
        try{
            date = df.parse(reminderDay+" "+reminderMonth+" "+reminderYear);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Data nuk lejohet ne kete format !");
            return;
        }
        


 
        
        if(date.before(today)){
           JOptionPane.showMessageDialog(this, "Data duhet te jete ne ditet ne vijim !");
            
        }else{
        
            try{
                Reminders r = new Reminders();

                r.setRemindersCity(1);
                r.setRemindersDate(date);
                r.setRemindersTitle(reminderTitle);
                r.setRemindersDescription(reminderDesc);
                if(share)
                    r.setRemindersShared(true);
                else
                   r.setRemindersShared(false); 
                if(isset){
                try{
                    temp = Short.parseShort(reminderTemp);
                    if(temp<-60 || temp>60)
                        throw new Exception();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Temperatura nuk lejohet ne kete format !");
                    return;            
                }
                r.setRemindersHigher(temp);
                r.setRemindersIsset(true);
                }
                    
                if(!isset)
                    r.setRemindersIsset(false);
                
                r.setRemindersUser(user.getUsername());
               
                
                remindRepo.addReminder(r);
                JOptionPane.showMessageDialog(this, "Reminder u shtua me sukses !");
                Home h = new Home();
                h.checkUser(user.getUsername(), user.getPassword());
                h.setVisible(true);
                dispose();
            }catch(Exception e){
                System.out.println(e);
            }
        }
        
    }
    
    
    private void dateDayActionPerformed(java.awt.event.ActionEvent evt) { }
    private void conditionActionPerformed(java.awt.event.ActionEvent evt) { }
    private void dateYearActionPerformed(java.awt.event.ActionEvent evt) { }
    private void tempActionPerformed(java.awt.event.ActionEvent evt) { }
    
    private void cityActionPerformed(java.awt.event.ActionEvent evt) { }
    private void dateMonthActionPerformed(java.awt.event.ActionEvent evt) { }
    private void titleActionPerformed(java.awt.event.ActionEvent evt) { }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReminder;
    private javax.swing.JButton addWeather;
    private javax.swing.JButton addWeather1;
    private javax.swing.JLabel celsious;
    private javax.swing.JTextField city;
    private javax.swing.JSeparator cityBorder;
    private javax.swing.JLabel cityText;
    private javax.swing.JLabel condJlabel;
    private javax.swing.JTextField dateDay;
    private javax.swing.JComboBox dateMonth;
    private javax.swing.JTextField dateYear;
    private javax.swing.JTextArea desc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jseperatorTemp;
    private javax.swing.JCheckBox shared;
    private javax.swing.JTextField temp;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
